Desafio-Frontend-Mvc/Controllers/EnderecoController.cs
using Desafio_Core.Models;
using Desafio_Frontend_Mvc.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Desafio_Frontend_Mvc.Controllers
{
    public class EnderecoController : Controller
    {
        private readonly IEnderecoService _enderecoService;
        public EnderecoController(IEnderecoService enderecoService)
        {
            _enderecoService = enderecoService; 
        }

        // GET: Endereco
        public async Task<IActionResult> Index()
        {
            var enderecos = await _enderecoService.GetAllAsync();
            return View(enderecos);
        }

        // GET: Endereco/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Endereco/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FuncionarioId,Rua,Numero,CEP,Cidade,Estado")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                _enderecoService.CreateAsync(endereco);
                return RedirectToAction(nameof(Index));
            }
            return View(endereco);
        }

        // GET: Endereco/Edit/5
        public async Task<IActionResult> Edit(long id)
        {
            if (id <= 0) return NotFound();

            var resultado = await _enderecoService.GetAllAsync();
            var endereco = resultado.FirstOrDefault(x => x.Id == id);

            if (endereco is null || endereco.Id.Equals(0)) return NotFound();

            return View(endereco);
        }

        // POST: Endereco/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,FuncionarioId,Rua,Numero,CEP,Cidade,Estado")] Endereco endereco)
        {
            if (id != endereco.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _enderecoService.UpdateByIdAsync(endereco);
                }
                catch
                {
                    if (!await EnderecoExiste(endereco.Id)) 
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(endereco);
        }

        // GET: Endereco/Delete/5
        public async Task<IActionResult> Delete(long id)
        {
            if (id <= 0) return NotFound();

            var resultado = await _enderecoService.GetAllAsync();
            var endereco = resultado.FirstOrDefault(x => x.Id == id);

            if (endereco == null) return NotFound();

            return View(endereco);
        }

        // POST: Endereco/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("Id,FuncionarioId,Rua,Numero,CEP,Cidade,Estado")] Endereco endereco)
        {
            await _enderecoService.DeleteAsync(endereco);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> EnderecoExiste(long id)
        {
            var resultado = await _enderecoService.GetAllAsync();
            return resultado.Any(e => e.Id == id);
        }
    }
}

Desafio-Frontend-Mvc/Controllers/EntrevistaController.cs
using Desafio_Core.Models;
using Desafio_Frontend_Mvc.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Desafio_Frontend_Mvc.Controllers
{
    public class EntrevistaController : Controller
    {
        private readonly IEntrevistaService _entrevistaService;

        public EntrevistaController(IEntrevistaService entrevistaService)
        {
            _entrevistaService = entrevistaService;
        }

        // GET: EntrevistaController
        public async Task<IActionResult> Index()
        {
            var entrevistas = await _entrevistaService.GetAllAsync();
            return View(entrevistas);
        }

        // GET: EntrevistaController/Details/5
        public ActionResult Details(long id)
        {
            return View();
        }

        // GET: EntrevistaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EntrevistaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,FuncionarioId,Empresa,DataEntrevista,Salario,Responsavel")] Entrevista entrevista)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _entrevistaService.CreateAsync(entrevista);
                    return RedirectToAction(nameof(Index));
                }
                return View(entrevista);
            }
            catch
            {
                return View();
            }
        }

        // GET: EntrevistaController/Edit/5
        public async Task<ActionResult> Edit(long id)
        {
            if (id <= 0) return NotFound();

            var resultado = await _entrevistaService.GetAllAsync();
            var entrevista = resultado.FirstOrDefault(x => x.Id == id);

            if (entrevista is null || entrevista.Id.Equals(0)) return NotFound();

            return View(entrevista);
        }

        // POST: EntrevistaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(long id, [Bind("Id,FuncionarioId,Empresa,DataEntrevista,Salario,Responsavel")] Entrevista entrevista)
        {
            try
            {
                if (id != entrevista.Id) return NotFound();

                if (ModelState.IsValid)
                {
                    try
                    {
                        _entrevistaService.UpdateByIdAsync(entrevista);
                    }
                    catch
                    {
                        if (!await EntrevistaExiste(entrevista.Id)) 
                            return NotFound();
                        else
                            throw;
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(entrevista);
            }
            catch
            {
                return View();
            }
        }

        // GET: EntrevistaController/Delete/5
        public async Task<ActionResult> Delete(long id)
        {
            if (id <= 0) return NotFound();

            var resultado = await _entrevistaService.GetAllAsync();
            var entrevista = resultado.FirstOrDefault(x => x.Id == id);

            if (entrevista == null) return NotFound();

            return View(entrevista);
        }

        // POST: EntrevistaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(long id, [Bind("Id,FuncionarioId,Empresa,DataEntrevista,Salario,Responsavel")] Entrevista entrevista)
        {
            try
            {
                await _entrevistaService.DeleteAsync(entrevista);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private async Task<bool> EntrevistaExiste(long id)
        {
            var resultado = await _entrevistaService.GetAllAsync();
            return resultado.Any(e => e.Id == id);
        }
    }
}

Desafio-Frontend-Mvc/Controllers/FuncionarioController.cs
using Desafio_Core.Models;
using Desafio_Frontend_Mvc.Interfaces;
using Desafio_Frontend_Mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace Desafio_Frontend_Mvc.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly IFuncionarioService _funcionarioService;

        public FuncionarioController(IFuncionarioService funcionarioService)
        {
            _funcionarioService = funcionarioService;
        }

        public async Task<IActionResult> Index()
        {
            var produtos = await _funcionarioService.GetAllAsync();
            return View(produtos);
        }

        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _funcionarioService.GetAllAsync();
            if (!funcionario.Any(m => m.Id == id))
            {
                return NotFound();
            }

            var entrevistaHistorico = await _funcionarioService.RetornarHistoricoEntrevistaAsync(id);

            var viewModel = new FuncionarioDetalhes
            {
                Funcionario = funcionario.FirstOrDefault(m => m.Id == id),
                EntrevistaHistorico = entrevistaHistorico
            };

            return View(viewModel);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Idade, Mae, Pai")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                _funcionarioService.CreateAsync(funcionario);
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resultado = await _funcionarioService.GetAllAsync();
            var funcionario = resultado.FirstOrDefault(x => x.Id == id);

            if (funcionario is null || funcionario.Id.Equals(0))
            {
                return NotFound();
            }
            return View(funcionario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Nome,Idade, Mae, Pai")] Funcionario funcionario)
        {
            if (id != funcionario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _funcionarioService.UpdateByIdAsync(funcionario);
                }
                catch
                {
                    if (!await FuncionarioExiste(funcionario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null) return NotFound();

            var resultado = await _funcionarioService.GetAllAsync();
            var funcionario = resultado.FirstOrDefault(x => x.Id == id);

            if (funcionario == null) return NotFound();

            return View(funcionario);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(long id, [Bind("Id,Nome,Idade,Mae,Pai")] Funcionario funcionario)
        {
            await _funcionarioService.DeleteAsync(funcionario);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> FuncionarioExiste(long id)
        {
            var resultado = await _funcionarioService.GetAllAsync();
            return resultado.Any(e => e.Id == id);
        }
    }
}

Desafio-Frontend-Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DESAFIO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Desafio_Frontend_Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FIAP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Endereco" asp-action="Index">Endereços</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entrevista" asp-action="Index">Entrevistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FIAP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>